// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// r_flags.cpp
cpp11::list mdbx_flags_();
extern "C" SEXP _mdbx_mdbx_flags_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_flags_());
  END_CPP11
}
// r_flags.cpp
cpp11::strings mdbx_env_get_flags_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_get_flags_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_get_flags_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_flags.cpp
void mdbx_env_set_flags_(cpp11::sexp env, cpp11::strings flags, bool on);
extern "C" SEXP _mdbx_mdbx_env_set_flags_(SEXP env, SEXP flags, SEXP on) {
  BEGIN_CPP11
    mdbx_env_set_flags_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(flags), cpp11::as_cpp<cpp11::decay_t<bool>>(on));
    return R_NilValue;
  END_CPP11
}
// r_flags.cpp
bool mdbx_env_sync_(cpp11::sexp env, bool force, bool nonblock);
extern "C" SEXP _mdbx_mdbx_env_sync_(SEXP env, SEXP force, SEXP nonblock) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_sync_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env), cpp11::as_cpp<cpp11::decay_t<bool>>(force), cpp11::as_cpp<cpp11::decay_t<bool>>(nonblock)));
  END_CPP11
}
// r_mdbx.cpp
void mdbx_initialize_();
extern "C" SEXP _mdbx_mdbx_initialize_() {
  BEGIN_CPP11
    mdbx_initialize_();
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_version_();
extern "C" SEXP _mdbx_mdbx_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_version_());
  END_CPP11
}
// r_mdbx.cpp
cpp11::sexp mdbx_env_open_(std::string path, bool readonly, bool subdir, double max_dbs, double map_size, double max_readers, int mode, cpp11::strings extra_flags);
extern "C" SEXP _mdbx_mdbx_env_open_(SEXP path, SEXP readonly, SEXP subdir, SEXP max_dbs, SEXP map_size, SEXP max_readers, SEXP mode, SEXP extra_flags) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_open_(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<bool>>(readonly), cpp11::as_cpp<cpp11::decay_t<bool>>(subdir), cpp11::as_cpp<cpp11::decay_t<double>>(max_dbs), cpp11::as_cpp<cpp11::decay_t<double>>(map_size), cpp11::as_cpp<cpp11::decay_t<double>>(max_readers), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(extra_flags)));
  END_CPP11
}
// r_mdbx.cpp
void mdbx_env_close_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_close_(SEXP env) {
  BEGIN_CPP11
    mdbx_env_close_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
bool mdbx_env_is_open_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_is_open_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_is_open_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_mdbx.cpp
int mdbx_env_reader_check_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_reader_check_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_reader_check_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_mdbx.cpp
std::string mdbx_env_path_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_path_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_path_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::sexp mdbx_txn_begin_(cpp11::sexp env, bool write, cpp11::strings extra_flags);
extern "C" SEXP _mdbx_mdbx_txn_begin_(SEXP env, SEXP write, SEXP extra_flags) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_txn_begin_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env), cpp11::as_cpp<cpp11::decay_t<bool>>(write), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(extra_flags)));
  END_CPP11
}
// r_mdbx.cpp
void mdbx_txn_commit_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_txn_commit_(SEXP txn) {
  BEGIN_CPP11
    mdbx_txn_commit_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
void mdbx_txn_abort_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_txn_abort_(SEXP txn) {
  BEGIN_CPP11
    mdbx_txn_abort_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
std::string mdbx_txn_state_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_txn_state_(SEXP txn) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_txn_state_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn)));
  END_CPP11
}
// r_mdbx.cpp
double mdbx_txn_id_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_txn_id_(SEXP txn) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_txn_id_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::sexp mdbx_get_(cpp11::sexp txn, cpp11::sexp key, cpp11::strings db);
extern "C" SEXP _mdbx_mdbx_get_(SEXP txn, SEXP key, SEXP db) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_get_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(key), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db)));
  END_CPP11
}
// r_mdbx.cpp
bool mdbx_put_(cpp11::sexp txn, cpp11::sexp key, cpp11::sexp value, bool overwrite, cpp11::strings db);
extern "C" SEXP _mdbx_mdbx_put_(SEXP txn, SEXP key, SEXP value, SEXP overwrite, SEXP db) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_put_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(key), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(value), cpp11::as_cpp<cpp11::decay_t<bool>>(overwrite), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db)));
  END_CPP11
}
// r_mdbx.cpp
bool mdbx_del_(cpp11::sexp txn, cpp11::sexp key, cpp11::strings db);
extern "C" SEXP _mdbx_mdbx_del_(SEXP txn, SEXP key, SEXP db) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_del_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(key), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_env_stat_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_stat_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_stat_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_txn_stat_(cpp11::sexp txn, cpp11::strings db);
extern "C" SEXP _mdbx_mdbx_txn_stat_(SEXP txn, SEXP db) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_txn_stat_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_env_info_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_info_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_info_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_txn_info_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_txn_info_(SEXP txn) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_txn_info_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn)));
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_scan_(cpp11::sexp txn, double limit, bool values, cpp11::strings db, cpp11::sexp start, bool reverse);
extern "C" SEXP _mdbx_mdbx_scan_(SEXP txn, SEXP limit, SEXP values, SEXP db, SEXP start, SEXP reverse) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_scan_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<double>>(limit), cpp11::as_cpp<cpp11::decay_t<bool>>(values), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(start), cpp11::as_cpp<cpp11::decay_t<bool>>(reverse)));
  END_CPP11
}
// r_mdbx.cpp
int mdbx_txn_live_count_();
extern "C" SEXP _mdbx_mdbx_txn_live_count_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_txn_live_count_());
  END_CPP11
}
// r_mdbx.cpp
int mdbx_env_txn_count_(cpp11::sexp env);
extern "C" SEXP _mdbx_mdbx_env_txn_count_(SEXP env) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_txn_count_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env)));
  END_CPP11
}
// r_mdbx.cpp
int mdbx_env_live_count_();
extern "C" SEXP _mdbx_mdbx_env_live_count_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_env_live_count_());
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_limits_(double pagesize);
extern "C" SEXP _mdbx_mdbx_limits_(SEXP pagesize) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_limits_(cpp11::as_cpp<cpp11::decay_t<double>>(pagesize)));
  END_CPP11
}
// r_mdbx.cpp
void mdbx_dbi_open_(cpp11::sexp txn, std::string name, bool create);
extern "C" SEXP _mdbx_mdbx_dbi_open_(SEXP txn, SEXP name, SEXP create) {
  BEGIN_CPP11
    mdbx_dbi_open_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<std::string>>(name), cpp11::as_cpp<cpp11::decay_t<bool>>(create));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
double mdbx_dbi_sequence_(cpp11::sexp txn, cpp11::strings db, double increment);
extern "C" SEXP _mdbx_mdbx_dbi_sequence_(SEXP txn, SEXP db, SEXP increment) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_dbi_sequence_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db), cpp11::as_cpp<cpp11::decay_t<double>>(increment)));
  END_CPP11
}
// r_mdbx.cpp
void mdbx_dbi_drop_(cpp11::sexp txn, cpp11::strings db, bool del);
extern "C" SEXP _mdbx_mdbx_dbi_drop_(SEXP txn, SEXP db, SEXP del) {
  BEGIN_CPP11
    mdbx_dbi_drop_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(db), cpp11::as_cpp<cpp11::decay_t<bool>>(del));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
cpp11::list mdbx_dbi_list_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_dbi_list_(SEXP txn) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_dbi_list_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn)));
  END_CPP11
}
// r_mdbx.cpp
void mdbx_test_check_(int rc);
extern "C" SEXP _mdbx_mdbx_test_check_(SEXP rc) {
  BEGIN_CPP11
    mdbx_test_check_(cpp11::as_cpp<cpp11::decay_t<int>>(rc));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
cpp11::integers mdbx_test_error_codes_();
extern "C" SEXP _mdbx_mdbx_test_error_codes_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_test_error_codes_());
  END_CPP11
}
// r_mdbx.cpp
int mdbx_test_result_true_();
extern "C" SEXP _mdbx_mdbx_test_result_true_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_test_result_true_());
  END_CPP11
}
// r_mdbx.cpp
int mdbx_test_thread_mismatch_(cpp11::sexp txn);
extern "C" SEXP _mdbx_mdbx_test_thread_mismatch_(SEXP txn) {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_test_thread_mismatch_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(txn)));
  END_CPP11
}
// r_mdbx.cpp
int mdbx_thread_mismatch_code_();
extern "C" SEXP _mdbx_mdbx_thread_mismatch_code_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mdbx_thread_mismatch_code_());
  END_CPP11
}
// r_mdbx.cpp
void mdbx_test_panic_stat_(cpp11::sexp env, bool info);
extern "C" SEXP _mdbx_mdbx_test_panic_stat_(SEXP env, SEXP info) {
  BEGIN_CPP11
    mdbx_test_panic_stat_(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(env), cpp11::as_cpp<cpp11::decay_t<bool>>(info));
    return R_NilValue;
  END_CPP11
}
// r_mdbx.cpp
void mdbx_test_panic_boundary_();
extern "C" SEXP _mdbx_mdbx_test_panic_boundary_() {
  BEGIN_CPP11
    mdbx_test_panic_boundary_();
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mdbx_mdbx_dbi_drop_",             (DL_FUNC) &_mdbx_mdbx_dbi_drop_,             3},
    {"_mdbx_mdbx_dbi_list_",             (DL_FUNC) &_mdbx_mdbx_dbi_list_,             1},
    {"_mdbx_mdbx_dbi_open_",             (DL_FUNC) &_mdbx_mdbx_dbi_open_,             3},
    {"_mdbx_mdbx_dbi_sequence_",         (DL_FUNC) &_mdbx_mdbx_dbi_sequence_,         3},
    {"_mdbx_mdbx_del_",                  (DL_FUNC) &_mdbx_mdbx_del_,                  3},
    {"_mdbx_mdbx_env_close_",            (DL_FUNC) &_mdbx_mdbx_env_close_,            1},
    {"_mdbx_mdbx_env_get_flags_",        (DL_FUNC) &_mdbx_mdbx_env_get_flags_,        1},
    {"_mdbx_mdbx_env_info_",             (DL_FUNC) &_mdbx_mdbx_env_info_,             1},
    {"_mdbx_mdbx_env_is_open_",          (DL_FUNC) &_mdbx_mdbx_env_is_open_,          1},
    {"_mdbx_mdbx_env_live_count_",       (DL_FUNC) &_mdbx_mdbx_env_live_count_,       0},
    {"_mdbx_mdbx_env_open_",             (DL_FUNC) &_mdbx_mdbx_env_open_,             8},
    {"_mdbx_mdbx_env_path_",             (DL_FUNC) &_mdbx_mdbx_env_path_,             1},
    {"_mdbx_mdbx_env_reader_check_",     (DL_FUNC) &_mdbx_mdbx_env_reader_check_,     1},
    {"_mdbx_mdbx_env_set_flags_",        (DL_FUNC) &_mdbx_mdbx_env_set_flags_,        3},
    {"_mdbx_mdbx_env_stat_",             (DL_FUNC) &_mdbx_mdbx_env_stat_,             1},
    {"_mdbx_mdbx_env_sync_",             (DL_FUNC) &_mdbx_mdbx_env_sync_,             3},
    {"_mdbx_mdbx_env_txn_count_",        (DL_FUNC) &_mdbx_mdbx_env_txn_count_,        1},
    {"_mdbx_mdbx_flags_",                (DL_FUNC) &_mdbx_mdbx_flags_,                0},
    {"_mdbx_mdbx_get_",                  (DL_FUNC) &_mdbx_mdbx_get_,                  3},
    {"_mdbx_mdbx_initialize_",           (DL_FUNC) &_mdbx_mdbx_initialize_,           0},
    {"_mdbx_mdbx_limits_",               (DL_FUNC) &_mdbx_mdbx_limits_,               1},
    {"_mdbx_mdbx_put_",                  (DL_FUNC) &_mdbx_mdbx_put_,                  5},
    {"_mdbx_mdbx_scan_",                 (DL_FUNC) &_mdbx_mdbx_scan_,                 6},
    {"_mdbx_mdbx_test_check_",           (DL_FUNC) &_mdbx_mdbx_test_check_,           1},
    {"_mdbx_mdbx_test_error_codes_",     (DL_FUNC) &_mdbx_mdbx_test_error_codes_,     0},
    {"_mdbx_mdbx_test_panic_boundary_",  (DL_FUNC) &_mdbx_mdbx_test_panic_boundary_,  0},
    {"_mdbx_mdbx_test_panic_stat_",      (DL_FUNC) &_mdbx_mdbx_test_panic_stat_,      2},
    {"_mdbx_mdbx_test_result_true_",     (DL_FUNC) &_mdbx_mdbx_test_result_true_,     0},
    {"_mdbx_mdbx_test_thread_mismatch_", (DL_FUNC) &_mdbx_mdbx_test_thread_mismatch_, 1},
    {"_mdbx_mdbx_thread_mismatch_code_", (DL_FUNC) &_mdbx_mdbx_thread_mismatch_code_, 0},
    {"_mdbx_mdbx_txn_abort_",            (DL_FUNC) &_mdbx_mdbx_txn_abort_,            1},
    {"_mdbx_mdbx_txn_begin_",            (DL_FUNC) &_mdbx_mdbx_txn_begin_,            3},
    {"_mdbx_mdbx_txn_commit_",           (DL_FUNC) &_mdbx_mdbx_txn_commit_,           1},
    {"_mdbx_mdbx_txn_id_",               (DL_FUNC) &_mdbx_mdbx_txn_id_,               1},
    {"_mdbx_mdbx_txn_info_",             (DL_FUNC) &_mdbx_mdbx_txn_info_,             1},
    {"_mdbx_mdbx_txn_live_count_",       (DL_FUNC) &_mdbx_mdbx_txn_live_count_,       0},
    {"_mdbx_mdbx_txn_stat_",             (DL_FUNC) &_mdbx_mdbx_txn_stat_,             2},
    {"_mdbx_mdbx_txn_state_",            (DL_FUNC) &_mdbx_mdbx_txn_state_,            1},
    {"_mdbx_mdbx_version_",              (DL_FUNC) &_mdbx_mdbx_version_,              0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mdbx(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
