# Generated by cpp11: do not edit by hand

mdbx_flags_ <- function() {
  .Call(`_mdbx_mdbx_flags_`)
}

mdbx_env_get_flags_ <- function(env) {
  .Call(`_mdbx_mdbx_env_get_flags_`, env)
}

mdbx_env_set_flags_ <- function(env, flags, on) {
  invisible(.Call(`_mdbx_mdbx_env_set_flags_`, env, flags, on))
}

mdbx_env_sync_ <- function(env, force, nonblock) {
  .Call(`_mdbx_mdbx_env_sync_`, env, force, nonblock)
}

mdbx_initialize_ <- function() {
  invisible(.Call(`_mdbx_mdbx_initialize_`))
}

mdbx_version_ <- function() {
  .Call(`_mdbx_mdbx_version_`)
}

mdbx_env_open_ <- function(path, readonly, subdir, max_dbs, map_size, max_readers, mode, extra_flags) {
  .Call(`_mdbx_mdbx_env_open_`, path, readonly, subdir, max_dbs, map_size, max_readers, mode, extra_flags)
}

mdbx_env_close_ <- function(env) {
  invisible(.Call(`_mdbx_mdbx_env_close_`, env))
}

mdbx_env_is_open_ <- function(env) {
  .Call(`_mdbx_mdbx_env_is_open_`, env)
}

mdbx_env_reader_check_ <- function(env) {
  .Call(`_mdbx_mdbx_env_reader_check_`, env)
}

mdbx_env_path_ <- function(env) {
  .Call(`_mdbx_mdbx_env_path_`, env)
}

mdbx_txn_begin_ <- function(env, write, extra_flags) {
  .Call(`_mdbx_mdbx_txn_begin_`, env, write, extra_flags)
}

mdbx_txn_commit_ <- function(txn) {
  invisible(.Call(`_mdbx_mdbx_txn_commit_`, txn))
}

mdbx_txn_abort_ <- function(txn) {
  invisible(.Call(`_mdbx_mdbx_txn_abort_`, txn))
}

mdbx_txn_state_ <- function(txn) {
  .Call(`_mdbx_mdbx_txn_state_`, txn)
}

mdbx_txn_id_ <- function(txn) {
  .Call(`_mdbx_mdbx_txn_id_`, txn)
}

mdbx_get_ <- function(txn, key, db) {
  .Call(`_mdbx_mdbx_get_`, txn, key, db)
}

mdbx_put_ <- function(txn, key, value, overwrite, db) {
  .Call(`_mdbx_mdbx_put_`, txn, key, value, overwrite, db)
}

mdbx_del_ <- function(txn, key, db) {
  .Call(`_mdbx_mdbx_del_`, txn, key, db)
}

mdbx_env_stat_ <- function(env) {
  .Call(`_mdbx_mdbx_env_stat_`, env)
}

mdbx_txn_stat_ <- function(txn, db) {
  .Call(`_mdbx_mdbx_txn_stat_`, txn, db)
}

mdbx_env_info_ <- function(env) {
  .Call(`_mdbx_mdbx_env_info_`, env)
}

mdbx_txn_info_ <- function(txn) {
  .Call(`_mdbx_mdbx_txn_info_`, txn)
}

mdbx_scan_ <- function(txn, limit, values, db, start, reverse) {
  .Call(`_mdbx_mdbx_scan_`, txn, limit, values, db, start, reverse)
}

mdbx_txn_live_count_ <- function() {
  .Call(`_mdbx_mdbx_txn_live_count_`)
}

mdbx_env_txn_count_ <- function(env) {
  .Call(`_mdbx_mdbx_env_txn_count_`, env)
}

mdbx_env_live_count_ <- function() {
  .Call(`_mdbx_mdbx_env_live_count_`)
}

mdbx_limits_ <- function(pagesize) {
  .Call(`_mdbx_mdbx_limits_`, pagesize)
}

mdbx_dbi_open_ <- function(txn, name, create) {
  invisible(.Call(`_mdbx_mdbx_dbi_open_`, txn, name, create))
}

mdbx_dbi_sequence_ <- function(txn, db, increment) {
  .Call(`_mdbx_mdbx_dbi_sequence_`, txn, db, increment)
}

mdbx_dbi_drop_ <- function(txn, db, del) {
  invisible(.Call(`_mdbx_mdbx_dbi_drop_`, txn, db, del))
}

mdbx_dbi_list_ <- function(txn) {
  .Call(`_mdbx_mdbx_dbi_list_`, txn)
}

mdbx_test_check_ <- function(rc) {
  invisible(.Call(`_mdbx_mdbx_test_check_`, rc))
}

mdbx_test_error_codes_ <- function() {
  .Call(`_mdbx_mdbx_test_error_codes_`)
}

mdbx_test_result_true_ <- function() {
  .Call(`_mdbx_mdbx_test_result_true_`)
}

mdbx_test_thread_mismatch_ <- function(txn) {
  .Call(`_mdbx_mdbx_test_thread_mismatch_`, txn)
}

mdbx_thread_mismatch_code_ <- function() {
  .Call(`_mdbx_mdbx_thread_mismatch_code_`)
}

mdbx_test_panic_stat_ <- function(env, info) {
  invisible(.Call(`_mdbx_mdbx_test_panic_stat_`, env, info))
}

mdbx_test_panic_boundary_ <- function() {
  invisible(.Call(`_mdbx_mdbx_test_panic_boundary_`))
}
